#abc=("computer")
#print(abc)
#starting position : ednding positin+1
#abc=("computer")
#print(abc[0:])
#abc=("this is nature of cool")
#print(len(abc))
#abc=("computer")
#print(abc[:4+1])
#abc=("computersdfasdf")
#print(abc[:5])
#abc=("comp_uter")
print(abc[0:3+1]+abc[5:10])
#abc=("computer")
#print(abc.find("t"))
abc=("today your class will stop after few days ago strted my class")
y=(abc.find("stop"))
print(abc[y:])
